package com.marko.rest.utils

import com.marko.domain.models.LicenseItem
import com.marko.domain.models.OwnerItem
import com.marko.domain.models.UserRepoItem
import com.marko.rest.models.LicenseDTO
import com.marko.rest.models.OwnerDTO
import com.marko.rest.models.UserReposItemDTO

internal fun LicenseDTO.toModel(): LicenseItem = LicenseItem(key, name, node_id, spdx_id, url)

internal fun OwnerDTO.toModel(): OwnerItem = OwnerItem(
    avatar_url,
    events_url,
    followers_url,
    following_url,
    gists_url,
    gravatar_id,
    html_url,
    id,
    login,
    node_id,
    organizations_url,
    received_events_url,
    repos_url,
    site_admin,
    starred_url,
    subscriptions_url,
    type,
    url
)

internal fun UserReposItemDTO.toModel(): UserRepoItem = UserRepoItem(
    allow_forking,
    archive_url,
    archived,
    assignees_url,
    blobs_url,
    branches_url,
    clone_url,
    collaborators_url,
    comments_url,
    commits_url,
    compare_url,
    contents_url,
    contributors_url,
    created_at,
    default_branch,
    deployments_url,
    description,
    disabled,
    description,
    events_url,
    fork,
    forks,
    forks_count,
    forks_url,
    full_name,
    git_commits_url,
    git_refs_url,
    git_tags_url,
    git_url,
    has_discussions,
    has_downloads,
    has_issues,
    has_pages,
    has_projects,
    has_wiki,
    homepage,
    hooks_url,
    html_url,
    id,
    is_template,
    issue_comment_url,
    issue_events_url,
    issues_url,
    keys_url,
    labels_url,
    language,
    languages_url,
    license?.toModel(),
    merges_url,
    milestones_url,
    mirror_url,
    name,
    node_id,
    notifications_url,
    open_issues,
    open_issues_count,
    owner.toModel(),
    private,
    pulls_url,
    pushed_at,
    releases_url,
    size,
    ssh_url,
    stargazers_count,
    stargazers_url,
    statuses_url,
    subscribers_url,
    subscription_url,
    svn_url,
    tags_url,
    teams_url,
    topics,
    trees_url,
    updated_at,
    url,
    visibility,
    watchers,
    watchers_count,
    web_commit_signoff_required
)